name: ci

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint (flake8)
        run: |
          flake8 src app tests --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 src app tests --count --exit-zero --max-complexity=12 --max-line-length=100 --statistics

      - name: Run tests
        env:
          PYTHONPATH: .
        run: |
          pytest -q
